import { APPROUTES } from '@/config/routes'

export const NAVIGATIONHEADER: any[] = [
	APPROUTES.HOME,
	APPROUTES.ORDERS,
	APPROUTES.CONSULTATIONS,
	APPROUTES.PRODUCTS,
	APPROUTES.CLIENTS,
	APPROUTES.ADVISORS
]
