name: Reporta un bug o inconsistencia
description: Informa de un bug o inconsistencia en la aplicacion
title: "🐛 "
labels: ["🐛 bug"]
projects: ["FOCCUS"]
body:
  - type: markdown
    attributes:
      value: |
        Por favor, rellene las siguientes secciones para ayudar a todos a identificar y corregir el fallo
  - type: textarea
    id: description
    attributes:
      label: Describa el problema
      placeholder: |
        Cuando hago clic aqui sucede esto.
        Este boton no hace lo que deberia.
        etc...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ¿Cuál es el resultado esperado?
      placeholder: Se espera que esto suceda, se vea o se comporte de la siguiente manera
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Pon aquí cualquier captura de pantalla o video (opcional)
  - type: markdown
    attributes:
      value: |
        ¡Gracias por informar de este problema!